AllCops:
  TargetRubyVersion: 2.7
Layout/LineLength:
  Max: 120 # Increase line length to 120
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes # Use double quotes ALL THE TIME!!!
Style/Documentation:
  Enabled: false # Disable Style/Documentation because...
